### PR TITLE
Hide Appointment Form if there's no hold nor return.

### LINKED ISSUE #940: Hide content on new appointment page when no appointment can be created
**Describe the bug**
Members can see an appointment form that doesn't make much sense

**To Reproduce**
1. Go to the new appointment page without any loans or holds

**Expected behavior**
It would be nice to clean this page up and hide the headings and other content since the member can't interact with them.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by ChaelCodes**
# What it does

closes #940 

Instead of showing the appointment form, we show a blurb explaining they cannot make an appointment with no holds nor returns.

# Why it is important

This makes the appointment page less cluttered for folks who can't make an appointment because they don't have a hold nor an item to return.

# UI Change Screenshot

Before | After
--- | ---
blurb telling user they cannot make an appointment, and then a form to make an appointment. | form is gone on schedule appointment page

# Implementation notes

* I moved the form into an if/else instead of it living outside the if. I handled it inside _form, so if this form is used anywhere else, the change will also apply.

# Your bandwidth for additional changes to this PR

_Please choose one of the following to help the project maintainers provide the appropriate level of support:_

- [x] I have the time and interest to make additional changes to this PR based on feedback.
- [x] I am interested in feedback but don't need to make the changes myself.
- [ ] I don't have time or interest in making additional changes to this work.
- [ ] Other or not sure (please describe):

_My weekday schedule is a little full, but every weekend, I have time to contribute._

### CODE REVIEW

File: test/system/appointments_test.rb [hunk 1]
```diff
@@ -77,6 +77,20 @@ def fill_in_optional_field(text)
     within(list_item_containing(@held_item2.complete_number)) { assert_text "Ready for pickup" }
   end
 
+  test "attempts to schedule an appointment with no holds" do
```
Comment (jim) [inline test/system/appointments_test.rb:80]: Thanks for adding a test for this.

File: app/views/account/appointments/_form.html.erb [hunk 2]
```diff
@@ -8,112 +8,111 @@
     </ul>
   <% end %>
 
-  <% if !can_schedule_appointment %>
-    <div class="toast toast-warning">
-      <p>You can only schedule an appointment if you have a tool on hold or that can be returned.</p>
-      <%= link_to "View Inventory", items_path, class: "btn btn-lg btn-default" %>
-    </div>
-  <% end %>
+  <% if can_schedule_appointment %>
```
Comment (jim) [inline app/views/account/appointments/_form.html.erb:11]: Putting both cases into an if/else like this makes the flow easier to see.

**Review by jim — APPROVED** [review]
This looks good to me. Thanks for the contribution.

Apologies for the late review, we moved recently and things are just getting settled.
